---
_extends: .github

repository:
  name: toktok-stack
  description: A snapshot of the complete software stack (excluding some external libraries and programs)
  topics: bazel, tox

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - "Codacy/PR Quality Review"
          - "LGTM analysis: Go"
          - "LGTM analysis: Python"
          - "Travis CI - Pull Request"
          - "cirrus-ci"
          - "code-review/reviewable"
