---
cirrus-ci_task:
  container:
    image: l.gcr.io/google/bazel:3.1.0
    cpu: 8
    memory: 12G
  configure_script:
    - apt-get update && apt-get install -y --no-install-recommends make libgmp-dev
    - git submodule update --init --depth=50 --recursive
  test_all_script:
    - TEST="bazel test -k
      --config=ci
      --config=clang
      --config=release
      //c-toxcore/...
      //go-toxcore-c/...
      //jtox/...
      //jvm-macros/...
      //jvm-toxcore-api/...
      //jvm-toxcore-c/...
      //py_toxcore_c/...
      //toxins/..."
    - $TEST || $TEST || $TEST || $TEST
