---
cirrus-ci_task:
  container:
    image: l.gcr.io/google/bazel:2.2.0
    cpu: 8
    memory: 12G
  configure_script:
    - wget https://repo1.maven.org/maven2/org/bytedeco/javacpp-presets/ffmpeg/3.4.1-1.4/ffmpeg-3.4.1-1.4-linux-x86_64.jar -O third_party/javacpp/ffmpeg/jar/ffmpeg-3.4.1-1.4-linux-x86_64.jar
    - wget https://repo1.maven.org/maven2/org/bytedeco/javacpp-presets/opencv/3.4.0-1.4/opencv-3.4.0-1.4-linux-x86_64.jar -O third_party/javacpp/opencv/jar/opencv-3.4.0-1.4-linux-x86_64.jar
    - git submodule update --init --depth=5 --recursive
    - tools/setup-ci
  test_all_script:
    - RUN_TEST="bazel test --config=release -k
        //c-toxcore/...
        //go-toxcore-c/...
        //py_toxcore_c/...
        //toxins/..."
    - $RUN_TEST || $RUN_TEST || $RUN_TEST
