language: generic
dist: trusty
sudo: required

addons:
  apt:
    packages:
    - yasm

before_install:
- wget https://github.com/bazelbuild/bazel/releases/download/0.9.0/bazel_0.9.0-linux-x86_64.deb
- sha256sum -c tools/bazel_0.9.0-linux-x86_64.deb.sha256
- sudo dpkg -i bazel_0.9.0-linux-x86_64.deb

#script: bazel build //...
script: bazel build //c-toxcore/... --verbose_failures | cat

git:
  depth: 1
