language: cpp
compiler: clang
dist: trusty

addons:
  apt:
    sources:
    - sourceline: 'ppa:beineri/opt-qt593-trusty'
    packages:
    - autopoint
    - libconfig-dev
    - libcv-dev
    - libhighgui-dev
    - libopenal-dev
    - qt59tools
    - qt59svg
    - yasm

before_install:
- wget https://github.com/bazelbuild/bazel/releases/download/0.9.0/bazel-0.9.0-without-jdk-installer-linux-x86_64.sh
- sha256sum -c tools/bazel-0.9.0-without-jdk-installer-linux-x86_64.sh.sha256
- chmod +x bazel-0.9.0-without-jdk-installer-linux-x86_64.sh
- ./bazel-0.9.0-without-jdk-installer-linux-x86_64.sh --user
- export PATH=$HOME/bin:$PATH

install:
- echo "build --jobs=10 --curses=no --verbose_failures" >> $HOME/.bazelrc
- echo "test --jobs=10 --curses=no --verbose_failures" >> $HOME/.bazelrc

script:
- bazel build //qtox/... && bazel test //qtox/...

git:
  depth: 1
  submodules_depth: 1
