language: cpp
compiler: clang
dist: trusty

addons:
  apt:
    packages:
    - autopoint
    - libasound2-dev
    - libcv-dev
    - libhighgui-dev
    - libopenal-dev

cache:
  directories:
  - $HOME/.cache/bazel

before_install:
- rm -rf $HOME/.cache/bazel/_bazel_$USER/install
- wget https://github.com/bazelbuild/bazel/releases/download/0.9.0/bazel-0.9.0-without-jdk-installer-linux-x86_64.sh
- sha256sum -c tools/bazel-0.9.0-without-jdk-installer-linux-x86_64.sh.sha256
- chmod +x bazel-0.9.0-without-jdk-installer-linux-x86_64.sh
- ./bazel-0.9.0-without-jdk-installer-linux-x86_64.sh --user
- export PATH=$HOME/bin:$PATH

install:
- echo "build --jobs=4 --curses=no --verbose_failures" >> $HOME/.bazelrc
- wget http://repo1.maven.org/maven2/org/bytedeco/javacpp-presets/ffmpeg/3.4.1-1.4/ffmpeg-3.4.1-1.4-linux-x86_64.jar -O third_party/javacpp/ffmpeg/jar/ffmpeg-3.4.1-1.4-linux-x86_64.jar
- wget http://repo1.maven.org/maven2/org/bytedeco/javacpp-presets/opencv/3.4.0-1.4/opencv-3.4.0-1.4-linux-x86_64.jar -O third_party/javacpp/opencv/jar/opencv-3.4.0-1.4-linux-x86_64.jar

script:
- TARGETS=""
- TARGETS="$TARGETS //c-toxcore/..."
- TARGETS="$TARGETS //echobot-jvm/..."
#- TARGETS="$TARGETS //go-toxcore-c/..."
#- TARGETS="$TARGETS //jtox/..."
- TARGETS="$TARGETS //jvm-macros/..."
- TARGETS="$TARGETS //jvm-toxcore-api/..."
- TARGETS="$TARGETS //jvm-toxcore-c/..."
#- TARGETS="$TARGETS //py_toxcore_c/..."
#- TARGETS="$TARGETS //qtox/..."
- TARGETS="$TARGETS //streambot-jvm/..."
#- TARGETS="$TARGETS //toxic/..."
- TARGETS="$TARGETS //toxins/..."
- bazel test $TARGETS || bazel build $TARGETS

git:
  depth: 1
  submodules_depth: 1
