---
language: cpp
compiler: clang
dist: xenial
os: linux

cache:
  directories:
    - $HOME/.cache/bazel/_bazel_$USER/cache/repos/v1/content_addressable 

jobs:
  include:
    - env: JOB=docker-build
      services: [docker]
      before_install: []
      install: []
      script: docker build tools -t toxchat/builder
    - env: JOB=bazel-docker
      services: [docker]
      addons: &addons
        apt:
          packages:
            - libasound-dev
            - libopenal-dev
            - libqt5svg5-dev
            - python3.5-dev
            - qttools5-dev
            - qttools5-dev-tools
      before_install: source tools/setup-bazel
      install: tools/setup-ci
      script:
        - echo 'build --config=docker-sandbox' >> $HOME/.bazelrc
        - bazel build
            //c-toxcore/...
            //go-toxcore-c/...
            //py_toxcore_c/...
            //toxins/...
            //third_party/...
    - env: JOB=bazel-local
      addons: *addons
      before_install: source tools/setup-bazel
      install: tools/setup-ci
      script:
        - bazel build
           //c-toxcore/...
           //echobot-jvm/...
           //go-toxcore-c/...
           //jtox/...
           //jvm-macros/...
           //jvm-toxcore-api/...
           //jvm-toxcore-c/...
           //py_toxcore_c/...
           //qtox/...
           //streambot-jvm/...
           //third_party/...
           //toxic/...
           //toxins/...

git:
  depth: 1
  submodules_depth: 5
