---
language: cpp
compiler: clang
dist: xenial
os: linux

cache:
  directories:
    - $HOME/.cache/bazel/_bazel_$USER/cache/repos/v1/content_addressable 

jobs:
  include:
    - env: JOB=bazel-docker
      services: [docker]
      addons: &addons
        apt:
          packages:
            - libasound-dev
            - libqt5svg5-dev
            - libssl-dev
            - libx264-dev
            - python3.5-dev
            - qttools5-dev
            - qttools5-dev-tools
      before_install: source tools/setup-bazel
      install: tools/setup-ci
      script:
        - echo 'build --config=docker-sandbox' >> $HOME/.bazelrc
        - bazel build -k
            //c-toxcore/...
            //go-toxcore-c/...
            //py_toxcore_c/...
            //toxins/...
        - sha256sum -c tools/checksums/linux.sha256
    - env: JOB=bazel-local
      addons: *addons
      before_install: source tools/setup-bazel
      install: tools/setup-ci
      script:
        - bazel test -k
           --config=release
           //apidsl/...
           //cedar/...
           //ci-tools/...
           //c-toxcore/...
           //c-toxcore-hs/...
           //dockerfiles/...
           //echobot-jvm/...
           //go-toxcore-c/...
           //hs-cimple/...
           //hs-github-tools/...
           //hs-msgpack-binary/...
           //hs-msgpack-rpc-conduit/...
           //hs-msgpack-types/...
           //hs-schema/...
           //hs-tokstyle/...
           //hs-toxcore/...
           //hs-toxcore-c/...
           //js-toxcore-c/...
           //jtox/...
           //jvm-macros/...
           //jvm-sbt-plugins/...
           //jvm-toxcore-api/...
           //jvm-toxcore-c/...
           //py_toxcore_c/...
           //qtox/...
           //spec/...
           //streambot-jvm/...
           //third_party/...
           //tools/...
           //toxic/...
           //toxins/...
           //website/...

git:
  depth: 1
  submodules_depth: 5
