#with ((import <nixpkgs> { }).pkgsMusl);
with (import <nixpkgs> { });

{
  ghc = haskellPackages.ghcWithPackages.override { installDocumentation = false; } (
    p: with p; [
      Diff
      MonadRandom
      QuickCheck
      aeson
      aeson-pretty
      array
      async
      attoparsec
      base
      base16-bytestring
      binary
      binary-conduit
      brick
      bytestring
      case-insensitive
      casing
      clock
      conduit
      conduit-extra
      containers
      cryptohash
      data-binary-ieee754
      data-default-class
      data-fix
      deepseq
      directory
      edit-distance
      entropy
      exceptions
      expiring-cache-map
      extra
      file-embed
      filepath
      generic-arbitrary
      github
      groom
      happy-lib
      hashable
      hspec
      html
      http-client
      http-client-tls
      http-conduit
      http-media
      http-types
      insert-ordered-containers
      integer-gmp
      iproute
      language-c
      lens-family
      microlens
      microlens-mtl
      microlens-th
      monad-control
      monad-logger
      monad-parallel
      monad-validate
      mtl
      network
      optparse-applicative
      parallel
      pretty
      prettyprinter
      prettyprinter-ansi-terminal
      process
      quickcheck-instances
      quickcheck-text
      random
      recursion-schemes
      resourcet
      saltine
      scientific
      servant
      servant-server
      split
      stm
      suspend
      tabular
      text
      text-zipper
      time
      timers
      transformers
      transformers-compat
      unix
      unliftio-core
      unordered-containers
      uuid
      vector
      vty
      wai
      wai-cors
      wai-extra
      warp
      word-wrap
      yaml
    ]
  );
}
