flags: {}
packages:
- hs-msgpack/
- hs-msgpack-rpc/
- hs-msgpack-types/
- hs-schema/
- hs-toxcore/
- hs-toxcore-c/
- github-tools/
- tokstyle/
extra-deps:
- data-default-instances-base-0.1.0.1
- saltine-0.0.1.0
resolver: lts-10.2
