---
version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - release

jobs:
  release:
    docker:
      - image: l.gcr.io/google/bazel:2.2.0

    steps:
      - checkout
      - run: &config
          echo 'build --jobs=50 --curses=no --verbose_failures' >> $HOME/.bazelrc;
          echo 'build --config=linux'                           >> $HOME/.bazelrc;
          echo "build --config=$CC"                             >> $HOME/.bazelrc;
          echo 'build --config=remote'                          >> $HOME/.bazelrc;
      - run: bazel test --config=release //c-toxcore/toxcore/...
