---
name: ci

# These checks only run on pull requests as they don't need to publish anything
# on push. See docker.yml for jobs that run on both pull requests and pushes.
on:
  pull_request:
    branches: [master]

jobs:
  buildifier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install
        run: |
          wget -O buildifier https://github.com/bazelbuild/buildtools/releases/download/4.2.4/buildifier-linux-amd64
          chmod +x buildifier
      - name: Check
        run: ./buildifier --lint=warn --warnings=all -mode diff WORKSPACE $(find . -type f -name "BUILD.*")

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install mypy
        run: pip install mypy
      - name: Run mypy
        run: make mypy
