---
name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pull latest toktok-stack image
        run: docker pull toxchat/toktok-stack:latest
      - name: Build toktok-stack base image
        run: make build-workspace
      - name: Build //third_party
        if: ${{ github.event_name == 'push' }}
        run: make -C tools/built
      - name: Push images to DockerHub
        if: ${{ github.event_name == 'push' }}
        run: make push

  buildifier:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          wget -O buildifier https://github.com/bazelbuild/buildtools/releases/download/4.2.4/buildifier-linux-amd64
          chmod +x buildifier
      - name: Check
        run: ./buildifier --lint=warn --warnings=all -mode diff WORKSPACE $(find . -type f -name "BUILD.*")
