---
name: ci

# These checks only run on pull requests as they don't need to publish anything
# on push. See docker.yml for jobs that run on pushes.
on:
  pull_request:
    branches: [master]

jobs:
  common:
    uses: TokTok/ci-tools/.github/workflows/common-ci.yml@master

  docker-haskell:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build toxchat/toktok-stack:haskell
        uses: docker/build-push-action@v4
        with:
          file: tools/built/src/Dockerfile.haskell
          tags: toxchat/toktok-stack:haskell
          cache-from: type=registry,ref=toxchat/toktok-stack:haskell

  docker-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build toxchat/toktok-stack:latest-third_party
        uses: docker/build-push-action@v4
        with:
          file: tools/built/src/Dockerfile.third_party
          tags: toxchat/toktok-stack:latest-third_party
          cache-from: type=registry,ref=toxchat/toktok-stack:latest-third_party

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build toxchat/toktok-stack:latest
        run: docker build -t toxchat/toktok-stack:latest -f tools/built/src/Dockerfile .

      - name: Build toxchat/toktok-stack:latest-release
        run: docker build -t toxchat/toktok-stack:latest-release -f tools/built/src/Dockerfile.release .

      - name: Run tests in toxchat/toktok-stack:latest-release
        if: ${{ contains(github.event.pull_request.title, 'chore(deps)') }}
        run: tools/built/bazel_test release

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install mypy
        run: pip install mypy
      - name: Run mypy
        run: make mypy
