---
name: ci

# These checks only run on pull requests as they don't need to publish anything
# on push. See docker.yml for jobs that run on pushes.
on:
  pull_request:
    branches: [master]

jobs:
  docker-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build toxchat/toktok-stack:latest-third_party
        uses: docker/build-push-action@v2
        with:
          file: tools/built/src/Dockerfile.third_party
          tags: toxchat/toktok-stack:latest-third_party
          cache-from: type=registry,ref=toxchat/toktok-stack:latest-third_party

      - name: Build toxchat/toktok-stack:latest
        uses: docker/build-push-action@v2
        with:
          file: tools/built/src/Dockerfile
          tags: toxchat/toktok-stack:latest
          cache-from: type=registry,ref=toxchat/toktok-stack:latest

      - name: Build toxchat/toktok-stack:latest-release
        uses: docker/build-push-action@v2
        with:
          file: tools/built/src/Dockerfile.release
          tags: toxchat/toktok-stack:latest-release
          cache-from: type=registry,ref=toxchat/toktok-stack:latest-release

      - name: Build and test the whole toktok-stack in release mode
        if: ${{ contains(github.event.pull_request.title, 'chore(deps)') }}
        run: tools/built/bazel_test release

  buildifier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install
        run: |
          wget -O buildifier https://github.com/bazelbuild/buildtools/releases/download/4.2.4/buildifier-linux-amd64
          chmod +x buildifier
      - name: Check
        run: ./buildifier --lint=warn --warnings=all -mode diff WORKSPACE $(find . -type f -name "BUILD.*")

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install mypy
        run: pip install mypy
      - name: Run mypy
        run: make mypy
