---
name: docker

on:
  push:
    branches: [master]

jobs:
  docker-third_party:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: tools/built/src/Dockerfile.third_party
          tags: toxchat/toktok-stack:latest-third_party
          cache-from: type=registry,ref=toxchat/toktok-stack:latest-third_party
          cache-to: type=inline

  docker:
    runs-on: ubuntu-latest
    needs: [docker-third_party]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: tools/built/src/Dockerfile
          tags: toxchat/toktok-stack:latest
          cache-from: type=registry,ref=toxchat/toktok-stack:latest
          cache-to: type=inline

  docker-release:
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: tools/built/src/Dockerfile.release
          tags: toxchat/toktok-stack:latest-release
          cache-from: type=registry,ref=toxchat/toktok-stack:latest-release
          cache-to: type=inline

  docker-fastbuild:
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: tools/built/src/Dockerfile.fastbuild
          tags: toxchat/toktok-stack:latest-fastbuild
          cache-from: type=registry,ref=toxchat/toktok-stack:latest-fastbuild
          cache-to: type=inline

  docker-dev:
    runs-on: ubuntu-latest
    needs: [docker-fastbuild]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: tools/built/src/Dockerfile.dev
          tags: toxchat/toktok-stack:latest-dev
          cache-from: type=registry,ref=toxchat/toktok-stack:latest-dev
          cache-to: type=inline

  docker-debug:
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: tools/built/src/Dockerfile.debug
          tags: toxchat/toktok-stack:latest-debug
          cache-from: type=registry,ref=toxchat/toktok-stack:latest-debug
          cache-to: type=inline

  docker-asan:
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: tools/built/src/Dockerfile.asan
          tags: toxchat/toktok-stack:latest-asan
          cache-from: type=registry,ref=toxchat/toktok-stack:latest-asan
          cache-to: type=inline

  docker-msan:
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: tools/built/src/Dockerfile.msan
          tags: toxchat/toktok-stack:latest-msan
          cache-from: type=registry,ref=toxchat/toktok-stack:latest-msan
          cache-to: type=inline

  docker-tsan:
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: tools/built/src/Dockerfile.tsan
          tags: toxchat/toktok-stack:latest-tsan
          cache-from: type=registry,ref=toxchat/toktok-stack:latest-tsan
          cache-to: type=inline

  kythe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build Kythe tables
        run: make build-kythe
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Kythe image to DockerHub
        run: make push-kythe
