---
name: kythe

# Run on push and once a week to keep the images from bitrotting and to
# identify issues while no commits are being pushed.
on:
# push:
#   branches: [master]
# pull_request:
#   branches: [master]
  schedule:
    - cron: "52 2 * * 0"

jobs:
  kythe-tables:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: tools/kythe/Dockerfile
          tags: toxchat/kythe-tables:latest
          cache-from: type=registry,ref=toxchat/kythe-tables:latest
          cache-to: type=inline
          push: ${{ github.event_name == 'push' }}

  kythe-serving:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    needs: [kythe-tables]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: dockerfiles/kythe/serving
          tags: toxchat/kythe-serving:latest
          cache-from: type=registry,ref=toxchat/kythe-serving:latest
          cache-to: type=inline
          push: true
